update: readme and clean up zshrc to separate personal

diff --git a/inst_macos b/inst_macos
--- a/inst_macos
+++ b/inst_macos
@@ -1,27 +1,48 @@
 #!/bin/bash
 
-## xcode command line tools
-xcode-select --install
-
-## homebrew
-curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash < /dev/null
-
-## iterm2
-brew install --cask iterm2
-
-## tmux
-brew install tmux
-
-## neovim
-curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
-tar xzf nvim-macos.tar.gz
-./nvim-osx64/bin/nvim
-
-## web browser
-brew install --cask arc
-
-## notes
-brew install --cask obsidian
-
 ln -s "$HOME/.dotfiles/.zshrc" "$HOME/.zshrc"
 ln -s "$HOME/.dotfiles/.config" "$HOME/.config"
+mkdir -p $HOME/.config/tmux/sessions
+# Finder: disable window animations and Get Info animations
+defaults write com.apple.finder DisableAllAnimations -bool true
+# Don’t animate opening applications from the Dock
+defaults write com.apple.dock launchanim -bool false
+# Remove the animation when hiding/showing the Dock
+defaults write com.apple.dock autohide-time-modifier -float 0
+# Don’t automatically rearrange Spaces based on most recent use
+defaults write com.apple.dock mru-spaces -bool false
+# When performing a search, search the current folder by default
+defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
+# Show the main window when launching Activity Monitor
+defaults write com.apple.ActivityMonitor OpenMainWindow -bool true
+# Visualize CPU usage in the Activity Monitor Dock icon
+defaults write com.apple.ActivityMonitor IconType -int 5
+# Show all processes in Activity Monitor
+defaults write com.apple.ActivityMonitor ShowCategory -int 0
+# Sort Activity Monitor results by CPU usage
+defaults write com.apple.ActivityMonitor SortColumn -string "CPUUsage"
+defaults write com.apple.ActivityMonitor SortDirection -int 0
+## xcode command line tools
+xcode-select --install
+## homebrew
+curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash < /dev/null
+if ! command -v brew &> /dev/null; then
+    echo "homebrew could not be found. aborting."
+    exit 1
+fi
+## iterm2
+brew install --cask iterm2
+## tmux
+brew install tmux
+## neovim
+brew install neovim
+## web browser
+brew install --cask arc
+## notes
+brew install --cask obsidian
+## yabai - window/space manager
+brew install koekeishiya/formulae/yabai
+yabai --start-service
+## skhd - yabai hotkeys
+brew install koekeishiya/formulae/skhd
+skhd --start-service
